#!/bin/bash

no_color='\033[0m'
green='\033[1;32m'

echo -e "$green uninstalling libre office$no_color"
sudo pacman -Rs "$(pacman -Qsq | grep libreoffice)"

sudo pacman -Sy steam
yes | sudo pacman -Sy python-pip telegram neofetch micro git

sudo pip install -U pip


' ' | sudo paru -Sy inxi
