#!/bin/bash

sudo pacman --noconfirm -Sy firefox unzip

sudo kwriteconfig5 --file "/usr/share/applications/chromium.desktop" --group "Desktop Entry" --key "Exec" "/usr/bin/chromium --force-dark-mode %U"

zip="$HOME/Desktop/firefox.zip"
ff_conf="$HOME/.mozilla/firefox"

rm "$zip"
curl -L gmanka.tk/arch/config/firefox.zip --output "$zip"

rm -rf "$ff_conf"
mkdir -p "$ff_conf"
unzip -qq "$zip" -d "$ff_conf"
rm "$zip"
