#!/bin/bash

echo 'Using gmanka profile for archinstall'
echo 'Root password will be set to "1"'
echo 'Connected disks:'
echo ''
lsblk -io KNAME,TYPE,SIZE,MODEL
echo ''
echo 'WARNING: /dev/sda will FULLY WIPED'
echo 'Press enter to continue and FULLY WIPE /dev/sda'

read -p ''

# pacman -Syu archinstall archlinux-keyring

# archinstall --config https://gmanka.tk/archc/config.json --disk-layout https://gmanka.tk/arch/disk-layout.json --creds https://gmanka.tk/arch/creds.json
