#!/bin/bash

kdir="$HOME/.local/share/konsole"
mkdir "$kdir/shortcuts"

kwriteconfig5 --file "$HOME/.config/konsolerc" --group "Desktop Entry" --key "DefaultProfile" "gmanka.profile"

kwriteconfig5 --file "$HOME/.config/konsolerc" --group "Shortcut Schemes" --key "Current Scheme" "gmanka.shortcuts"

curl -L 'gmanka.tk/arch/config/gmanka.profile' --output "$kdir/gmanka.profile"
curl -L 'gmanka.tk/arch/config/gmanka.shortcuts' --output "$kdir/shortcuts/gmanka.shortcuts"
