#!/bin/bash

# git repo: https://github.com/gmankab/gmankab.github.io/arch
# license: GNU General Public License v3 - https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-gpl-v3.0.md

# you can delete or comment tweak if you don't need it


no_color='\033[0m'
green='\033[1;32m'
blue='\033[1;34m'
red='\033[1;31m'

echo -e "$red WARNING: this script will change your name and email in git, and will wipe your zsh settings"
echo -e "$green it was written for arch KDE Plasma Theme Edition (Flagship) from$blue https://archlinuxgui.in/download.html$no_color"
echo -e "$green press enter to continue$no_color"
read -r

sudo rm '/etc/pacman.conf'
sudo curl -L 'gmanka.tk/arch/config/pacman.conf' --output '/etc/pacman.conf'
sudo pacman -Sy

echo -e "$green configuring kde$no_color"
sh <(curl -sSL gmanka.tk/arch/kde)

echo -e "$green configuring konsole$no_color"
sh <(curl -sSL gmanka.tk/arch/konsole)

echo -e "$green configuring git$no_color"
sh <(curl -sSL gmanka.tk/arch/git)

echo -e "$green installing firefox addons$no_color"
sh <(curl -sSL gmanka.tk/arch/firefox)

# echo -e "$green installing apps$no_color"
# sh <(curl -sSL gmanka.tk/arch/apps)

zsh
