#!/bin/bash

no_color='\033[0m'
green='\033[1;32m'

sudo pacman -Sy

# you can delete or comment tweak if you don't need it

echo -e "$green installing fonts$no_color"
sh <(curl -sSL gmanka.tk/arch/fonts)

echo -e "$green changing scale, font dpi and system fonts$no_color"
sh <(curl -sSL gmanka.tk/arch/scale)

echo -e "$green configuring konsole$no_color"
sh <(curl -sSL gmanka.tk/arch/konsole)

echo -e "$green uninstalling libre office$no_color"
sudo pacman -Rs $(pacman -Qsq | grep libreoffice) 