#!/bin/bash

# git repo: https://github.com/gmankab/gmankab.github.io/arch
# license: GNU General Public License v3 - https://github.com/IQAndreas/markdown-licenses/blob/master/gnu-gpl-v3.0.md

# you can delete or comment tweak if you don't need it

no_color='\033[0m'
green='\033[1;32m'
blue='\033[1;34m'

echo -e "$green WARNING: please run this script only on arch KDE Plasma Theme Edition (Flagship) from$blue https://archlinuxgui.in/download.html$no_color"
echo -e "$green press enter to continue$no_color"
read -r

sudo pacman -Sy

echo -e "$green adding multilib repo$no_color"
sudo kwriteconfig5 --file "/etc/pacman.conf" --group "multilib" --key "Include" "/etc/pacman.d/mirrorlist"

echo -e "$green syncing pacman databases$no_color"
sudo pacman -Sy

echo -e "$green configuring kde$no_color"
sh <(curl -sSL gmanka.tk/arch/kde)

echo -e "$green configuring konsole$no_color"
sh <(curl -sSL gmanka.tk/arch/konsole)

echo -e "$green configuring git$no_color"
sh <(curl -sSL gmanka.tk/arch/git)

echo -e "$green installing firefox extensions$no_color"
sh <(curl -sSL gmanka.tk/arch/firefox)

echo -e "$green installing apps$no_color"
sh <(curl -sSL gmanka.tk/arch/apps)
