#!/bin/bash

# sudo pacman --noconfirm -Sy zsh git

# sh -c "$(curl -fsSL raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
sh -c "$(curl -fsSL raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# rm -rf "$HOME/.zshrc.pre-oh-my-zsh"
# sudo chsh -s /bin/zsh "$USER"
