#!/bin/bash

sudo pacman --noconfirm -Rn zsh
rm -rf "$HOME/.zshrc"
sudo pacman --noconfirm -Sy zsh git
sh -c "$(curl -fsSL raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
sudo chsh -s /bin/zsh "$USER"
