#!/bin/bash

sudo pacman --noconfirm -Rnc zsh
rm "$HOME/.zshrc"
sudo rm -rf "/etc/zsh"
sudo pacman --noconfirm -Sy zsh git
sh -c "$(curl -fsSL raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
sudo chsh -s /bin/zsh "$USER"
